'use client';
import Image from 'next/image';import {ArrowUpRight,Search,ShoppingBag,Trash2,X} from 'lucide-react';import {useEffect,useMemo,useState} from 'react';import type {StoreItem} from '@/lib/ebay-store';

const filters=['All','English','Japanese','Sealed'] as const;
const CART_KEY='poke-haus-cart-v1';
export function InventoryShowcase({items}:{items:StoreItem[]}){
  const [filter,setFilter]=useState<(typeof filters)[number]>('All');const [query,setQuery]=useState('');const [cartIds,setCartIds]=useState<string[]>([]);const [cartOpen,setCartOpen]=useState(false);const [ready,setReady]=useState(false);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(CART_KEY)??'[]');if(Array.isArray(saved))setCartIds(saved.filter(id=>typeof id==='string'));}catch{localStorage.removeItem(CART_KEY)}finally{setReady(true)}},[]);
  useEffect(()=>{if(ready)localStorage.setItem(CART_KEY,JSON.stringify(cartIds))},[cartIds,ready]);
  const shown=useMemo(()=>items.filter(item=>(filter==='All'||item.category===filter)&&item.title.toLowerCase().includes(query.toLowerCase())),[items,filter,query]);
  const cart=useMemo(()=>cartIds.map(id=>items.find(item=>item.id===id)).filter((item):item is StoreItem=>Boolean(item)),[cartIds,items]);
  const total=useMemo(()=>cart.reduce((sum,item)=>sum+Number(item.price.replace(/[^0-9.-]+/g,'')),0),[cart]);
  const toggleCart=(id:string)=>setCartIds(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);
  return <><section className="inventorySection" id="inventory"><div className="container">
    <div className="inventoryTop"><div><h2 className="display">Fresh from the vault.</h2><p>Real listings from our eBay store. Prices and availability can change quickly.</p></div><label className="inventorySearch"><Search size={18}/><span className="srOnly">Search inventory</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cards or sets"/></label></div>
    <div className="inventoryControls"><div className="filterRow" aria-label="Filter inventory">{filters.map(name=><button key={name} onClick={()=>setFilter(name)} className={filter===name?'active':''}>{name}</button>)}</div><button className="cartTrigger" onClick={()=>setCartOpen(true)}><ShoppingBag size={18}/> Cart <span>{cart.length}</span></button></div>
    <div className="productGrid">{shown.map(item=>{const selected=cartIds.includes(item.id);return <article className="productCard" key={item.id}><a className="productImage" href={item.url} target="_blank" rel="noopener noreferrer"><Image src={item.image} alt={item.title} fill sizes="(max-width: 600px) 50vw, (max-width: 1000px) 33vw, 25vw"/></a><div className="productInfo"><span className="productCondition">{item.condition}</span><h3>{item.title}</h3><div className="productBuy"><strong>{item.price}</strong><a href={item.url} target="_blank" rel="noopener noreferrer">Details <ArrowUpRight size={15}/></a></div><button className={selected?'addCart added':'addCart'} onClick={()=>toggleCart(item.id)}>{selected?'Added to cart':'Add to cart'}</button></div></article>})}</div>
    {!shown.length&&<p className="emptyProducts">No cards match that search. Try another card, set, or category.</p>}
    <div className="inventoryFoot"><a className="btn shopPrimary" href="https://www.ebay.com/str/thepokehaus28" target="_blank" rel="noopener noreferrer">Browse all eBay listings <ArrowUpRight size={18}/></a></div>
  </div></section>{cartOpen&&<div className="cartBackdrop" onMouseDown={event=>{if(event.currentTarget===event.target)setCartOpen(false)}}><aside className="cartDrawer" role="dialog" aria-modal="true" aria-labelledby="cart-title"><div className="cartHead"><div><span>Your saved picks</span><h2 id="cart-title">Card cart</h2></div><button aria-label="Close cart" onClick={()=>setCartOpen(false)}><X/></button></div>{cart.length?<><div className="cartItems">{cart.map(item=><div className="cartItem" key={item.id}><div className="cartThumb"><Image src={item.image} alt="" fill sizes="72px"/></div><div><strong>{item.title}</strong><span>{item.price}</span><a href={item.url} target="_blank" rel="noopener noreferrer">Open listing <ArrowUpRight size={13}/></a></div><button aria-label={`Remove ${item.title}`} onClick={()=>toggleCart(item.id)}><Trash2 size={17}/></button></div>)}</div><div className="cartBottom"><div className="cartTotal"><span>Listing total</span><strong>${total.toFixed(2)}</strong></div><p>eBay requires each listing to be added on eBay before payment. Open the listings above, add them there, then continue to your eBay cart.</p><a className="btn shopPrimary" href="https://cart.ebay.com/sc/view" target="_blank" rel="noopener noreferrer">Continue to eBay cart <ArrowUpRight size={18}/></a></div></>:<div className="cartEmpty"><ShoppingBag size={36}/><h3>Your cart is empty</h3><p>Add cards from the shop and they’ll stay saved on this device.</p></div>}</aside></div>}</>
}
