'use client';
import {FormEvent,useMemo,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Link as LinkIcon} from 'lucide-react';
import {SiteHeader} from '@/components/site-header';

const types=['Small stack','Binder','Boxes / tins','Large bulk collection','Reverse holo stack'];
const rates={bulk:.5,premium:.75,reverse:.02} as const;
type Counts={bulk:number;premium:number;reverse:number};
const countFields:[keyof Counts,string,string][]=[
  ['bulk','V / VMAX / VSTAR / ex','$0.50 each'],['premium','Full Art / IR / Gold / Rainbow','$0.75 each'],
  ['reverse','Reverse holos','$20 per 1,000'],
];

export default function Sell(){
  const [step,setStep]=useState(1);const [kind,setKind]=useState('Binder');const [counts,setCounts]=useState<Counts>({bulk:0,premium:0,reverse:0});
  const [details,setDetails]=useState({name:'',email:'',phone:'',sellerRoute:'San Antonio local meetup',payoutMethod:'Cash App',payoutDetails:'',mediaLink:'',notes:''});const [accepted,setAccepted]=useState(false);const [status,setStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle');const [error,setError]=useState('');
  const estimate=useMemo(()=>Math.floor(counts.bulk*rates.bulk+counts.premium*rates.premium+counts.reverse*rates.reverse),[counts]);
  const knownCards=counts.bulk+counts.premium+counts.reverse;
  const updateCount=(key:keyof Counts,value:string)=>setCounts(current=>({...current,[key]:Math.max(0,Number.parseInt(value,10)||0)}));
  const updateDetail=(key:keyof typeof details,value:string)=>setDetails(current=>({...current,[key]:value}));
  const canContinue=step!==4||(details.name.trim()!==''&&/^\S+@\S+\.\S+$/.test(details.email));
  async function submit(event:FormEvent){event.preventDefault();if(!accepted){setError('Please accept the Terms and Shipping & Payout Policy first.');return}setStatus('sending');setError('');try{const response=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'sell',collectionType:kind,counts,estimate:`$${estimate} bulk estimate`,...details})});const data=await response.json();if(response.ok)setStatus('sent');else{setStatus('error');setError(data.error??'Please try again.')}}catch{setStatus('error');setError('Connection problem. Please try again.')}}
  return <><SiteHeader/><main><section className="pageHero"><div className="container"><h1 className="display">Sell us your Pokémon bulk.</h1><p>Get a simple estimate in minutes. San Antonio sellers can choose a convenient local meetup; everyone else can ship their bulk to us.</p></div></section><form className="container wizard" onSubmit={submit}><aside className="wizardNav">{['Collection & handoff','Bulk calculator','Photos & notes','Contact & payout','Review estimate','Send request'].map((label,index)=><div className={step===index+1?'active':''} key={label}>{index+1}. {label}</div>)}</aside><section className="card sellWizard"><div className="wizardStep">STEP {step} OF 6</div>
    {step===1&&<><h2>Tell us about your bulk</h2><p className="muted">Choose the closest collection size, then tell us how you want to hand it off.</p><div className="options">{types.map(type=><button type="button" className={'option '+(kind===type?'selected':'')} onClick={()=>setKind(type)} key={type}><span className={kind===type?'radio selected':'radio'}/> {type}</button>)}</div><h3 style={{marginTop:28}}>How will we receive it?</h3><div className="options"><button type="button" className={'option '+(details.sellerRoute==='San Antonio local meetup'?'selected':'')} onClick={()=>updateDetail('sellerRoute','San Antonio local meetup')}><span className={details.sellerRoute==='San Antonio local meetup'?'radio selected':'radio'}/> San Antonio local meetup</button><button type="button" className={'option '+(details.sellerRoute==='Ship my bulk'?'selected':'')} onClick={()=>updateDetail('sellerRoute','Ship my bulk')}><span className={details.sellerRoute==='Ship my bulk'?'radio selected':'radio'}/> Ship my bulk</button></div><div className="estimateNote"><strong>{details.sellerRoute==='San Antonio local meetup'?'Local seller:':'Shipping seller:'}</strong> {details.sellerRoute==='San Antonio local meetup'?'We’ll arrange a safe, convenient public meetup in San Antonio after reviewing your request. We are an online eBay store, not a walk-in retail shop.':'We’ll email packing and shipping instructions after reviewing your request. Seller-paid tracked shipping applies unless agreed otherwise.'}</div></>}
    {step===2&&<><h2>Bulk pricing calculator</h2><p className="muted">Enter approximate quantities. The estimate updates instantly and rounds down to a whole dollar.</p><div className="calculatorLayout"><div className="calculatorFields">{countFields.map(([key,label,rate])=><div className="calculatorRow" key={key}><div><label htmlFor={`count-${key}`}>{label}</label><span>{rate}</span></div><input id={`count-${key}`} type="number" inputMode="numeric" min="0" value={counts[key]||''} placeholder="0" onChange={event=>updateCount(key,event.target.value)}/></div>)}</div><aside className="liveEstimate"><span>Estimated bulk payout</span><strong>${estimate}</strong><small>{knownCards.toLocaleString()} bulk-priced cards</small></aside></div><div className="estimateNote"><strong>Three simple rates:</strong> V, VMAX, VSTAR and ex are $0.50 each; Full Art, Illustration Rare, Gold and Rainbow cards are $0.75 each; reverse holos are $20 per 1,000.</div></>}
    {step===3&&<><h2>Photos and collection notes</h2><p className="muted">Paste an optional Google Drive, Dropbox, iCloud, or album link. Make sure anyone with the link can view it.</p><div className="field"><label htmlFor="media-link">Photo / video share link</label><div className="inputIcon"><LinkIcon size={18}/><input id="media-link" type="url" value={details.mediaLink} onChange={event=>updateDetail('mediaLink',event.target.value)} placeholder="https://…"/></div></div><div className="field" style={{marginTop:18}}><label htmlFor="sell-notes">Anything else we should know?</label><textarea id="sell-notes" rows={5} value={details.notes} onChange={event=>updateDetail('notes',event.target.value)} placeholder="Sets, conditions, standout cards, sealed items…"/></div></>}
    {step===4&&<><h2>How can we reach and pay you?</h2><div className="formGrid"><div className="field"><label htmlFor="seller-name">Full name</label><input id="seller-name" required value={details.name} onChange={event=>updateDetail('name',event.target.value)}/></div><div className="field"><label htmlFor="seller-email">Email</label><input id="seller-email" type="email" required value={details.email} onChange={event=>updateDetail('email',event.target.value)}/></div><div className="field"><label htmlFor="seller-phone">Phone (optional)</label><input id="seller-phone" value={details.phone} onChange={event=>updateDetail('phone',event.target.value)}/></div><div className="field"><label htmlFor="payout-method">Preferred payout</label><select id="payout-method" value={details.payoutMethod} onChange={event=>updateDetail('payoutMethod',event.target.value)}><option>Cash App</option><option>Venmo</option><option>ACH</option></select></div><div className="field"><label htmlFor="payout-details">Payout handle (optional)</label><input id="payout-details" value={details.payoutDetails} onChange={event=>updateDetail('payoutDetails',event.target.value)} placeholder="$cashtag or @username"/></div></div></>}
    {step===5&&<><h2>Review your estimate</h2><div className="reviewEstimate"><span>Estimated bulk payout</span><strong>${estimate}</strong><small>Final payout may change after count, condition and authenticity verification.</small></div><div className="reviewRows"><div><span>Collection</span><strong>{kind}</strong></div><div><span>Handoff</span><strong>{details.sellerRoute}</strong></div><div><span>Bulk-priced cards</span><strong>{knownCards.toLocaleString()}</strong></div><div><span>Reply to</span><strong>{details.email}</strong></div></div><label className="termsCheck"><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)}/> I accept the Terms and Shipping & Payout Policy and understand this is an estimate, not a final offer.</label></>}
    {step===6&&(status==='sent'?<div className="submitState"><div className="successIcon"><Check size={38}/></div><h2>Request sent.</h2><p>Your collection details were delivered to <strong>sell@thepokehaus.com</strong>. We’ll reply to {details.email}.</p></div>:<div className="submitState"><h2>Ready to send?</h2><p>Your calculator results, collection details, and contact information will be sent securely to <strong>sell@thepokehaus.com</strong>.</p><button className="btn primary" disabled={status==='sending'}>{status==='sending'?'Sending request…':'Send collection request'}</button>{error&&<div className="formNotice error" role="alert">{error}</div>}</div>)}
    {status!=='sent'&&<div className="wizardActions"><button type="button" className="btn" disabled={step===1||status==='sending'} onClick={()=>setStep(current=>Math.max(1,current-1))}><ArrowLeft size={18}/> Back</button>{step<6&&<button type="button" className="btn primary" disabled={!canContinue} onClick={()=>setStep(current=>current+1)}>Continue <ArrowRight size={18}/></button>}</div>}
  </section></form></main></>;
}
