const { chromium } = require('playwright');
(async()=>{
  const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
  const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:3000',{waitUntil:'networkidle'});
  await page.screenshot({path:'work/home-desktop.png',fullPage:true});
  const headline=await page.locator('h1').innerText();
  await page.goto('http://127.0.0.1:3000/sell',{waitUntil:'networkidle'});
  for(let i=0;i<5;i++) await page.getByRole('button',{name:'Continue'}).click();
  const finalStep=await page.getByText('Ready to submit').isVisible();
  await page.setViewportSize({width:390,height:844});
  await page.goto('http://127.0.0.1:3000/sell',{waitUntil:'networkidle'});
  await page.screenshot({path:'work/sell-mobile.png',fullPage:true});
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://127.0.0.1:3000/admin',{waitUntil:'networkidle'});
  await page.screenshot({path:'work/admin-desktop.png',fullPage:true});
  console.log(JSON.stringify({headline,finalStep,errors},null,2));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
